/**
 * Document export — plain text, structured JSON, and print/PDF HTML.
 *
 * Rules:
 *  - Only clinician-approved documents can be exported (copy/text/JSON/PDF).
 *  - Draft print previews are always watermarked "DRAFT — NOT CLINICIAN
 *    APPROVED".
 *  - Exports contain document content only: never system instructions,
 *    encryption material, provider internals, or generation warnings.
 *  - Every export is written to the audit trail by the caller.
 */
import {
  APPROVED_DOC_STATUSES,
  DAP_SECTIONS,
  DOC_STATUS_LABELS,
  FORMULATION_SECTIONS,
  objectiveMissingItems,
  type DapNote,
  type DocSegment,
  type TreatmentGoal,
  type TreatmentPlanDoc,
} from '../db/documentSchema';

export interface ExportOptions {
  /** How the client appears in the header. */
  clientIdentifier: string;
  clinicianName?: string;
  documentTitle?: string;
  includeEvidenceRefs: boolean;
  includeVersionInfo: boolean;
}

export class ExportNotAllowedError extends Error {}

export function isApprovedDoc(doc: { reviewStatus: string }): boolean {
  return APPROVED_DOC_STATUSES.includes(doc.reviewStatus as (typeof APPROVED_DOC_STATUSES)[number]);
}

export function assertExportAllowed(doc: { reviewStatus: string }): void {
  if (!isApprovedDoc(doc)) {
    throw new ExportNotAllowedError(
      'Only clinician-approved documents can be exported. Draft output is available as a watermarked print preview only.',
    );
  }
}

const DRAFT_LABEL = 'DRAFT — NOT CLINICIAN APPROVED';

function segmentLine(segment: DocSegment, includeRefs: boolean): string {
  let line = segment.text;
  if (includeRefs && segment.sources.length > 0) {
    line += ` [${segment.sources.map((s) => s.label ?? s.refType).join('; ')}]`;
  }
  return line;
}

function header(
  doc: { reviewStatus: string; approvedAt?: string; reviewedBy?: string; version: number; generation: { providerLabel: string } },
  title: string,
  opts: ExportOptions,
): string[] {
  const lines = [title, '='.repeat(title.length)];
  if (!isApprovedDoc(doc)) lines.unshift(DRAFT_LABEL, '');
  lines.push(`Client: ${opts.clientIdentifier}`);
  if (opts.clinicianName) lines.push(`Clinician: ${opts.clinicianName}`);
  lines.push(`Status: ${DOC_STATUS_LABELS[doc.reviewStatus as keyof typeof DOC_STATUS_LABELS] ?? doc.reviewStatus}`);
  if (doc.approvedAt) lines.push(`Approved: ${doc.approvedAt.slice(0, 10)}${doc.reviewedBy ? ` by ${doc.reviewedBy}` : ''}`);
  if (opts.includeVersionInfo) {
    lines.push(`Version: ${doc.version} · Generated by: ${doc.generation.providerLabel}`);
  }
  lines.push('');
  return lines;
}

// ------------------------------------------------------------- DAP text

export function renderDapText(note: DapNote, opts: ExportOptions): string {
  const lines = header(note, opts.documentTitle ?? `DAP Note — Session ${note.sessionDate}`, opts);
  lines.push(`Session date: ${note.sessionDate}${note.sessionNumber ? ` (session ${note.sessionNumber})` : ''}`);
  lines.push(`Level of care: ${note.levelOfCare}`);
  lines.push('');
  for (const { key, label } of DAP_SECTIONS) {
    const segs = note.segments.filter((s) => s.section === key);
    lines.push(label.toUpperCase(), '-'.repeat(label.length));
    if (segs.length === 0) lines.push('(empty)');
    for (const segment of segs) lines.push(`• ${segmentLine(segment, opts.includeEvidenceRefs)}`);
    lines.push('');
  }
  return lines.join('\n');
}

// -------------------------------------------------------- Plan text

export function renderPlanText(plan: TreatmentPlanDoc, goals: TreatmentGoal[], opts: ExportOptions): string {
  const lines = header(plan, opts.documentTitle ?? `Master Treatment Plan — ${plan.planDate}`, opts);
  lines.push(`Plan date: ${plan.planDate}${plan.reviewDate ? ` · Review date: ${plan.reviewDate}` : ''}`);
  if (plan.diagnosesSnapshot.length > 0) lines.push(`Diagnoses/impressions: ${plan.diagnosesSnapshot.join('; ')}`);
  lines.push('');

  lines.push('PROBLEM STATEMENTS', '------------------');
  plan.problems.forEach((p, i) => {
    lines.push(`${i + 1}. ${p.text}${opts.includeEvidenceRefs && p.sources.length ? ` [${p.sources.map((s) => s.label ?? s.refType).join('; ')}]` : ''}`);
  });
  lines.push('');

  lines.push('EVIDENCED BY', '------------');
  plan.segments.filter((s) => s.section === 'evidenced-by').forEach((s) => lines.push(segmentLine(s, opts.includeEvidenceRefs)));
  lines.push('');

  lines.push('HOLISTIC CLINICAL FORMULATION', '-----------------------------');
  for (const { key, label } of FORMULATION_SECTIONS) {
    const segs = plan.segments.filter((s) => s.section === key);
    if (segs.length === 0) continue;
    lines.push(`${label}:`);
    segs.forEach((s) => lines.push(`  • ${segmentLine(s, opts.includeEvidenceRefs)}`));
  }
  lines.push('');

  lines.push('HIERARCHY OF CLINICAL NEEDS', '---------------------------');
  plan.hierarchy.forEach((n) => lines.push(`${n.rank}. ${n.need} — ${n.rationale}`));
  lines.push('');

  lines.push('GOAL PLAN', '---------');
  lines.push(plan.goalPlanRationale, plan.expectedImprovement, '');

  const planGoals = plan.goalsSnapshot ?? goals.filter((g) => plan.goalIds.includes(g.id));
  for (const goal of planGoals) {
    lines.push(`${goal.kind === 'short-term' ? 'Short-term goal' : 'Long-term goal'}: ${goal.title}`);
    if (goal.rationale) lines.push(`  Rationale: ${goal.rationale}`);
    for (const objective of goal.objectives) {
      lines.push(`  Objective: ${objective.description}`);
      if (objective.measurementMethod) lines.push(`    Measurement: ${objective.measurementMethod}`);
      if (objective.baseline) lines.push(`    Baseline: ${objective.baseline}`);
      if (objective.target) lines.push(`    Target: ${objective.target}`);
      if (objective.targetDate || objective.timeFrame) {
        lines.push(`    Time frame: ${objective.targetDate ?? objective.timeFrame}`);
      }
      const missing = objectiveMissingItems(objective);
      if (missing.length > 0) lines.push(`    NEEDS COMPLETION: ${missing.join('; ')}`);
      if (objective.therapistPlan.action) {
        lines.push(
          `    Therapist plan: ${objective.therapistPlan.action}` +
            (objective.therapistPlan.modality ? ` (${objective.therapistPlan.modality})` : '') +
            (objective.therapistPlan.frequency ? `, ${objective.therapistPlan.frequency}` : '') +
            (objective.therapistPlan.tracking ? `; tracked via ${objective.therapistPlan.tracking}` : ''),
        );
      }
    }
    lines.push('');
  }
  return lines.join('\n');
}

// ----------------------------------------------------------- JSON export

export function renderDocJson(
  doc: DapNote | TreatmentPlanDoc,
  goals: TreatmentGoal[],
  opts: ExportOptions,
): object {
  const base = {
    format: 'cockpit-clinical-document',
    version: 1,
    exportedAt: new Date().toISOString(),
    client: opts.clientIdentifier,
    clinician: opts.clinicianName,
    status: doc.reviewStatus,
    approvedAt: doc.approvedAt,
    reviewedBy: doc.reviewedBy,
    ...(opts.includeVersionInfo
      ? { documentVersion: doc.version, generationMethod: doc.generation.method, provider: doc.generation.providerLabel }
      : {}),
  };
  if ('sessionDate' in doc) {
    return {
      ...base,
      documentType: 'dap-note',
      sessionDate: doc.sessionDate,
      sessionNumber: doc.sessionNumber,
      levelOfCare: doc.levelOfCare,
      sections: Object.fromEntries(
        DAP_SECTIONS.map(({ key }) => [
          key,
          doc.segments
            .filter((s) => s.section === key)
            .map((s) => ({
              text: s.text,
              kind: s.kind,
              ...(opts.includeEvidenceRefs ? { sources: s.sources.map((x) => ({ type: x.refType, label: x.label, date: x.date })) } : {}),
            })),
        ]),
      ),
    };
  }
  return {
    ...base,
    documentType: 'treatment-plan',
    planDate: doc.planDate,
    reviewDate: doc.reviewDate,
    diagnoses: doc.diagnosesSnapshot,
    problems: doc.problems.map((p) => ({
      text: p.text,
      ...(opts.includeEvidenceRefs ? { sources: p.sources.map((s) => ({ type: s.refType, label: s.label })) } : {}),
    })),
    evidencedBy: doc.segments.filter((s) => s.section === 'evidenced-by').map((s) => s.text),
    formulation: Object.fromEntries(
      FORMULATION_SECTIONS.map(({ key, label }) => [
        label,
        doc.segments.filter((s) => s.section === key).map((s) => s.text),
      ]),
    ),
    hierarchy: doc.hierarchy.map((n) => ({ rank: n.rank, need: n.need, rationale: n.rationale })),
    goalPlan: { rationale: doc.goalPlanRationale, expectedImprovement: doc.expectedImprovement },
    goals: (doc.goalsSnapshot ?? goals.filter((g) => doc.goalIds.includes(g.id))).map((g) => ({
      kind: g.kind,
      title: g.title,
      rationale: g.rationale,
      status: g.status,
      objectives: g.objectives.map((o) => ({
        description: o.description,
        measurementMethod: o.measurementMethod,
        baseline: o.baseline,
        target: o.target,
        targetDate: o.targetDate ?? o.timeFrame,
        progress: o.progress,
        therapistPlan: o.therapistPlan,
        needsCompletion: objectiveMissingItems(o),
      })),
    })),
  };
}

// ----------------------------------------------------------- print HTML

export function renderPrintHtml(text: string, title: string, isDraft: boolean): string {
  const watermark = isDraft
    ? `<div style="position:fixed;top:40%;left:0;right:0;text-align:center;transform:rotate(-24deg);font-size:44px;color:rgba(163,82,78,0.18);font-weight:800;pointer-events:none;">${DRAFT_LABEL}</div>
       <p style="color:#a3524e;font-weight:700;border:2px solid #a3524e;padding:8px 12px;display:inline-block;">${DRAFT_LABEL}</p>`
    : '';
  const safe = text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
  return `<!doctype html><html><head><meta charset="utf-8"><title>${title}</title>
<style>body{font:14px/1.6 -apple-system,'Segoe UI',Roboto,sans-serif;color:#22303c;max-width:760px;margin:32px auto;padding:0 24px;} pre{white-space:pre-wrap;font:inherit;}</style>
</head><body>${watermark}<pre>${safe}</pre></body></html>`;
}
